name: servo3d
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py310h5541b7b_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.15.1=hb03c661_0
  - assimp=5.4.3=hecf2907_1
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - backports.zstd=1.3.0=py310h69bd2ac_0
  - blinker=1.9.0=pyhff2d567_0
  - blosc=1.21.6=he440d0b_1
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - brotli-python=1.2.0=py310hba01987_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cli11=2.6.0=h54a6638_0
  - click=8.3.1=pyh8f84b5b_1
  - contourpy=1.3.2=py310h3788b33_0
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dash=3.3.0=pyhd8ed1ab_0
  - dbus=1.16.2=h24cb091_1
  - double-conversion=3.4.0=hecca717_0
  - embree=4.4.0=ha751380_1
  - flask=3.1.2=pyhd8ed1ab_0
  - fmt=12.0.0=h2b0788b_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py310h3406613_0
  - freetype=2.14.1=ha770c72_0
  - frozenlist=1.7.0=py310h9548a50_0
  - gl2ps=1.4.2=hae5d5c5_1
  - glew=2.2.0=h3abd4de_0
  - glfw=3.4=hb03c661_1
  - graphite2=1.3.14=hecca717_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.0=h6083320_0
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.6=nompi_h1b119a7_104
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhcf101f3_1
  - jsoncpp=1.9.6=hf42df4d_1
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py310haaf941d_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libboost=1.88.0=hd24cca6_7
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp21.1=21.1.7=default_h99862b1_3
  - libclang13=21.1.7=default_h746c552_3
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_1
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglu=9.0.3=h5888daf_1
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - libllvm20=20.1.8=hf7376ad_1
  - libllvm21=21.1.8=hf7376ad_0
  - liblzf=3.6=hb9d3cd8_3
  - liblzma=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.3=nompi_h11f7409_103
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libpq=18.1=hb80d175_3
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.51.1=hf4e2dac_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtheora=1.1.1=h4ab18f5_1006
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h54a6638_2
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libxslt=1.1.43=h711ed8c_1
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - loguru=0.7.3=pyh707e725_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib=3.10.8=py310hff52083_0
  - matplotlib-base=3.10.8=py310hfde16b3_0
  - mesalib=25.0.5=h57bcd07_2
  - msgpack-python=1.1.2=py310h03d9f68_1
  - multidict=6.7.0=py310h3406613_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.14.0=pyhcf101f3_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.12.0=h54a6638_1
  - numpy=2.2.6=py310hefbff90_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.47=haa7fec5_0
  - pillow=12.0.0=py310h5a73078_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - plotly=6.5.0=pyhd8ed1ab_0
  - proj=9.7.1=h99ae125_0
  - propcache=0.3.1=py310h89163eb_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pybind11-abi=4=hd8ed1ab_3
  - pyparsing=3.3.1=pyhcf101f3_0
  - pyside6=6.10.1=py310h2007e60_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.19=h3c07f61_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - qhull=2020.2=h434a139_5
  - qt6-main=6.10.1=hb82b983_4
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - retrying=1.4.2=pyhe01879c_0
  - scipy=1.15.2=py310h1d65ade_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_1
  - spirv-tools=2025.4=hb700be7_0
  - sqlite=3.51.1=h04a0ce9_1
  - tbb=2022.3.0=h8d10470_1
  - tinyobjloader=1.0.7=h59595ed_2
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.4=py310ha78b2d2_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - unicodedata2=17.0.0=py310h7c4b9e2_1
  - urllib3=2.6.2=pyhd8ed1ab_0
  - utfcpp=4.09=ha770c72_0
  - viskores=1.0.0=hca82ae8_3
  - vtk-base=9.5.2=py310h3aa82cb_5
  - wayland=1.24.0=hd6090a7_1
  - werkzeug=3.1.4=pyhcf101f3_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - wslink=2.5.0=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxshmfence=1.3.3=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - yarl=1.22.0=py310h3406613_0
  - zeromq=4.3.5=h387f397_9
  - zfp=1.0.1=h909a3a2_5
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - addict==2.4.0
      - asttokens==3.0.1
      - colorama==0.4.6
      - comm==0.2.3
      - configargparse==1.7.1
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - jedi==0.19.2
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-core==5.9.1
      - jupyterlab-widgets==3.0.16
      - markdown-it-py==4.0.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - nbformat==5.10.4
      - open3d==0.19.0
      - opencv-python==4.12.0.88
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyquaternion==0.9.9
      - pytz==2025.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - scikit-learn==1.7.2
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trimesh==4.10.1
      - tzdata==2025.3
      - wcwidth==0.2.14
      - widgetsnbextension==4.0.15
prefix: /home/user/miniconda3/envs/servo3d
